### PR TITLE
PR adding custom FOLLOW_POI

### PR DESCRIPTION
**Pull request by radarku**
First draft of a custom FOLLOW_POI message and supporting FOLLOW_MODE enum for review and comments.

### CODE REVIEW

**Comment by radarku** [comment]
@TSC21 
@thomas-watters-skydio
@jillh54

**Comment by TSC21** [comment]
@radarku although I agree this makes it all simpler, I believe the core problem will still remain and it also influences the Exploration Microservice. I would still argue it might be better to just reduce the UID to a uint32

**Comment by thomas-watters-skydio** [comment]
> @radarku although I agree this makes it all simpler, I believe the core problem will still remain and it also influences the Exploration Microservice. I would still argue it might be better to just reduce the UID to a uint32

What is the "core problem"? They resolved it by using uint64_t for the UID, so now its just a direct translation from POI_REPORT to FOLLOW_POI

**Comment by TSC21** [comment]
> > @radarku although I agree this makes it all simpler, I believe the core problem will still remain and it also influences the Exploration Microservice. I would still argue it might be better to just reduce the UID to a uint32
> 
> What is the "core problem"? They resolved it by using uint64_t for the UID, so now its just a direct translation from POI_REPORT to FOLLOW_POI

This is just a solution for this command. Doesn't solve the problem for all the Exploration Microservice commands that require a POI ID as well. We are not going to create a message for each of the other commands as well. We need a reasonable solution for all the commands, which means using a different resolution for the IDs (which was what was being suggested before).

**Comment by thomas-watters-skydio** [comment]
> > > @radarku although I agree this makes it all simpler, I believe the core problem will still remain and it also influences the Exploration Microservice. I would still argue it might be better to just reduce the UID to a uint32
> > 
> > 
> > What is the "core problem"? They resolved it by using uint64_t for the UID, so now its just a direct translation from POI_REPORT to FOLLOW_POI
> 
> This is just a solution for this command. Doesn't solve the problem for all the Exploration Microservice commands that require a POI ID as well. We are not going to create a message for each of the other commands as well. We need a reasonable solution for all the commands, which means using a different resolution for the IDs (which was what was being suggested before).

Two different conversations then. I have not been in the loop on the Exploration Microservice. I thought the issue was we were sticking to 64bit UID and we needed to find a way to do this within that constraint. If you are going to update POI_REPORT to only use 32 bit UID, then we need that change to move a lot faster, so that we can finally settle on a FOLLOW_POI message

**Comment by radarku** [comment]
Closing in favor of https://github.com/Dronecode/air-iop-definitions/pull/7

**Pull request closed without merging**
